
#pragma once


#define OVERLAP_PIX 230
#define OVERLAP_PCT 0.0598958333
#define OUTPUT_WIDTH (1920 * 2.0 * (1.0 - OVERLAP_PCT))
#define OUTPUT_HEIGHT 1080
#define OUTPUT_NUM_PIXELS (OUTPUT_WIDTH * OUTPUT_HEIGHT)
#define GOOD_NUM_PIXELS (1024.0 * 768.0 * 1.5)
#define OUTPUT_LARGE_FACTOR  ((float)OUTPUT_NUM_PIXELS / GOOD_NUM_PIXELS)
#define OUTPUT_LARGE_FACTOR_D_2  (OUTPUT_LARGE_FACTOR / 2.0)
#define ONE_D_OUTPUT_LARGE_FACTOR_D_2 (1.0 / OUTPUT_LARGE_FACTOR_D_2)

#define INPUT_WIDTH ((int)(OUTPUT_WIDTH * (1.0 / OUTPUT_LARGE_FACTOR_D_2)))
#define INPUT_HEIGHT ((int)(OUTPUT_HEIGHT * (1.0 / OUTPUT_LARGE_FACTOR_D_2)))
//
//#define INPUT_WIDTH_CACHED          1456
//#define INPUT_HEIGHT_CACHED         435
//#define OUTPUT_LARGE_FACTOR_D_2_CACHED 2.47879

#define OUTPUT_RAY 3769
//#define FIXING_CONSTANTS

// from before....

#define SCALE_CHANGE 5.0
#define ONE_D_SCALE_CHANGE (1.0 / SCALE_CHANGE)
#define DRAW_WEIGHT 2


#define NUM_BOUNCE_THREADS 5

